services:
  web:
    build:
      context: ..
      dockerfile: ./.docker/Dockerfile.ncjm
    container_name: ncjm_app
    env_file:
      - ../.env
    volumes:
      - ../public_collected/:/home/ncjm/public_collected
    working_dir: /home/ncjm/app
    command: ["gunicorn", "ncjm.wsgi:application", "--bind", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
