services:
  web:
    build:
      context: ..
      dockerfile: ./Dockerfile.ncjm
    container_name: ncjm_app
    env_file:
      - ../.env
    working_dir: /home/ncjm/app
    command: ["gunicorn", "ncjm.wsgi:application", "--bind", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: ncjm
      POSTGRES_USER: ncjm
      POSTGRES_PASSWORD: ncjm
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: