services:
  web:
    build:
      context: ..
      dockerfile: ./Dockerfile.ncjm
    container_name: ncjm_app
    env_file:
      - ../.env
    volumes:
      - ../ncjm/db.sqlite3:/home/ncjm/app/db.sqlite3
    working_dir: /home/ncjm/app
    command: ["gunicorn", "ncjm.wsgi:application", "--bind", "0.0.0.0:8000"]
    ports:
      - "8000:8000"

  nginx:
    image: nginx:alpine
    container_name: ncjm_nginx
    env_file:
      - ../.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../public_collected/:/home/ncjm/public_collected
      - ../.nginx.conf:/etc/nginx/nginx.conf
      - ${CERTS_ROOT}:/home/ncjm/certs
    depends_on:
      - web
